---
default_dns_addresses:
  - 178.22.122.100
  - 185.51.200.2

public_dns_addresses:
  - 8.8.8.8
  - 1.1.1.1

# ansible_ssh_private_key_file: './ssh/privates/ansible.id_rsa'
ansible_ssh_port: 22
ansible_user: ubuntu
ansible_netconf_ssh_config: True
